[profile.default]
ffi = true
build_info = true
extra_output = ['storageLayout', 'evm.gasEstimates']
fs_permissions = [{ access = "read", path = "/"}]
allow_paths = ["/"]
remappings=[
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/',
  '@sphinx/=node_modules/@sphinx-labs/plugins/contracts/foundry/'
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
goerli = "https://eth-goerli.g.alchemy.com/v2/demo"
optimism_goerli = "https://opt-goerli.g.alchemy.com/v2/demo"
arbitrum_goerli = "https://arb-goerli.g.alchemy.com/v2/demo"
bnb_smart_chain_testnet = "https://bsc-testnet.publicnode.com"
gnosis_chiado = "https://rpc.chiadochain.net"
polygon_mumbai = "https://polygon-mumbai.g.alchemy.com/v2/demo"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
